name: event_reservation_app
description: A chatbot integrated reservation system for events

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  table_calendar: ^3.0.9
  
  # Image handling dependencies
  image_picker: ^1.2.0
  image: ^4.5.4
  permission_handler: ^12.0.1
  logger: ^2.6.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/dove-icon.png"

flutter:
  uses-material-design: true
  
  # Add your assets here
  assets:
    - assets/images/
    - assets/icons/
    # - assets/fonts/Terraria.TTF
    # - assets/icons

  # fonts:
  #   - family: Terraria
  #     fonts:
  #       - asset: assets/fonts/Terraria.TTF